// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sneaker_Store.Data;

#nullable disable

namespace Sneaker_Store.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sneaker_Store.Model.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Efternavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Postnr")
                        .HasColumnType("int");

                    b.HasKey("KundeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Sneaker_Store.Model.Kvittering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Beskrivelse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Koebsdato")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPris")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Kvitteringer");
                });

            modelBuilder.Entity("Sneaker_Store.Model.Ordre", b =>
                {
                    b.Property<int>("OrdreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrdreId"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("SkoId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPris")
                        .HasColumnType("double");

                    b.HasKey("OrdreId");

                    b.HasIndex("KundeId");

                    b.HasIndex("SkoId");

                    b.ToTable("Ordrer");
                });

            modelBuilder.Entity("Sneaker_Store.Model.Sko", b =>
                {
                    b.Property<int>("SkoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkoId"));

                    b.Property<string>("Billede")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("LagerAntal")
                        .HasColumnType("int");

                    b.Property<string>("Maerke")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Pris")
                        .HasColumnType("double");

                    b.Property<int>("Str")
                        .HasColumnType("int");

                    b.HasKey("SkoId");

                    b.ToTable("Sko");

                    b.HasData(
                        new
                        {
                            SkoId = 1,
                            Billede = "https://picsum.photos/seed/nike-air-max/400/300",
                            LagerAntal = 12,
                            Maerke = "Nike",
                            Model = "Air Max",
                            Pris = 999.0,
                            Str = 44
                        },
                        new
                        {
                            SkoId = 2,
                            Billede = "https://picsum.photos/seed/asics-gel-1130/400/300",
                            LagerAntal = 5,
                            Maerke = "Asics",
                            Model = "Gel-1130",
                            Pris = 850.0,
                            Str = 38
                        },
                        new
                        {
                            SkoId = 3,
                            Billede = "https://picsum.photos/seed/adidas-campus/400/300",
                            LagerAntal = 1,
                            Maerke = "Adidas",
                            Model = "Campus",
                            Pris = 700.0,
                            Str = 42
                        },
                        new
                        {
                            SkoId = 4,
                            Billede = "https://picsum.photos/seed/asics-gel-kayano/400/300",
                            LagerAntal = 0,
                            Maerke = "Asics",
                            Model = "Gel-Kayano",
                            Pris = 999.0,
                            Str = 44
                        },
                        new
                        {
                            SkoId = 5,
                            Billede = "https://picsum.photos/seed/new-balance-530/400/300",
                            LagerAntal = 20,
                            Maerke = "New Balance",
                            Model = "530",
                            Pris = 799.0,
                            Str = 40
                        },
                        new
                        {
                            SkoId = 6,
                            Billede = "https://picsum.photos/seed/puma-suede-classic/400/300",
                            LagerAntal = 8,
                            Maerke = "Puma",
                            Model = "Suede Classic",
                            Pris = 599.0,
                            Str = 43
                        });
                });

            modelBuilder.Entity("Sneaker_Store.Model.Kvittering", b =>
                {
                    b.HasOne("Sneaker_Store.Model.Kunde", null)
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sneaker_Store.Model.Ordre", b =>
                {
                    b.HasOne("Sneaker_Store.Model.Kunde", null)
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sneaker_Store.Model.Sko", null)
                        .WithMany()
                        .HasForeignKey("SkoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
